name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  windows_6_9_3_msc_build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: jurplel/install-qt-action@v4
      with:
        # Directory to install Qt
        dir: # optional
        # Version of Qt to install
        version: '6.9.3'
        # Host platform
        host: # optional
        # Target platform for build
        target: 'desktop'
        # Architecture for Windows/Android
        arch: 'win64_msvc2022_64'
        # Whether or not to install Qt dependencies on Linux
        install-deps: 'true'
        # Additional Qt modules to install
        modules: 'qt5compat' #'qtscript qtscripttools'
        # Force a Qt mirror in case the default is not working
        #mirror: # optional
        # Whether or not to actually download Qt
        cached: # optional, default is false
        # Version of aqtinstall to use in case of issues
        aqtversion: # optional, default is ==0.8
        # Version of py7zr to use in case of issues
        py7zrversion: # optional, default is ==0.6
        # Any extra arguments to append to the back
        extra: # optional
        #tools: 'tools_ifw,4.0.1-202012091044,qt.tools.ifw.40'
    - name: Install 7Zip PowerShell Module
      shell: powershell
      run: Install-Module 7Zip4PowerShell -Force -Verbose
    - name: Install Qt and compile
      run: |
        d:
        dir 
        mkdir build
        dir
        dir build
        cmake -S . -B ./build
        dir
        cmake --build ./build --target all_build --config Release
        dir
        dir ./build

